#!/bin/bash

export ICINGA_PASSWORD=${ICINGA_PASSWORD:-$(pwgen -s 15 1)}

if [ -f /opt/custom_run ]; then
    chmod u+x /opt/custom_run
    echo "=>executing /opt/custom_run"
    /opt/custom_run
fi

/opt/setup/icinga2

cat <<-END

Starting Supervisor.
END

icinga2 daemon --validate

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n &
trap "supervisorctl shutdown && wait" SIGTERM
wait
